name: Main Branch Push or Pull request - Create main image and deploy to Google Cloud Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven and Run tests
        run: mvn clean package

      - name: Build Docker Image
        if: success()
        run: docker build -t zythaarcz/garbage-backend:latest .

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        run: docker push zythaarcz/garbage-backend:latest

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Pull image from Docker Hub
        run: |
          docker pull zythaarcz/garbage-backend:latest

      - name: Tag image for GCR
        if: success()
        run: docker tag zythaarcz/garbage-backend:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/garbage-backend:latest

      - name: Push image to GCR
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/garbage-backend:latest

      - name: Trigger Deployment in Google Cloud Run
        if: success()
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud run deploy garbage-backend-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/garbage-backend:latest \
            --platform managed \
            --region europe-west3 \
            --allow-unauthenticated \
            --service-account sep4-account@handy-parity-406210.iam.gserviceaccount.com
            --update-env-vars SEP_DB_USERNAME=${{ secrets.DB_USERNAME }},SEP_DB_PASSWORD=${{ secrets.DB_PASSWORD }}