name: Main Branch Push or Merge and Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven and Run tests
        run: mvn clean package

      - name: Build Docker Image
        if: success()
        run: docker build -t zythaarcz/garbage-backend:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        run: docker push zythaarcz/garbage-backend:latest

      - name: Pull image from Docker Hub
        if: success()
        run: |
          docker pull zythaarcz/garbage-backend:latest

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        run: |
          az login --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }}
        env:
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --name SEP4-backend --resource-group SEP4 --admin

      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl rollout status deployment/garbage-backend